-- default value
SHOW GP_ENABLE_QUERY_METRICS;
SELECT 1;

-- turn off
SET GP_ENABLE_QUERY_METRICS=OFF;
SHOW GP_ENABLE_QUERY_METRICS;
SELECT 1;

-- turn on
SET GP_ENABLE_QUERY_METRICS=ON;
SHOW GP_ENABLE_QUERY_METRICS;
SELECT 1;

-- turn off
SET GP_ENABLE_QUERY_METRICS=OFF;
SHOW GP_ENABLE_QUERY_METRICS;
SELECT 1;

-- reset
RESET GP_ENABLE_QUERY_METRICS;
SHOW GP_ENABLE_QUERY_METRICS;
SELECT 1;

-- default value
SHOW GP_QUERY_METRICS_PORT;
SELECT 1;
